myproject/urls.py
from django.contrib import admin
from django.urls import path, include
import notes.views

urlpatterns = [
    # path('', notes.views.index, name="index"),
    path('admin/', admin.site.urls),
    path('', include('notes.urls')),

]


notes/urls.py
from django.urls import path, include
from . import views
from .views import AjaxHandlerView
import sharedNotes.views as snote

app_name = "notes"
# app_name will help us do a reverse look-up latter.
urlpatterns = [
    path('', views.index, name="index"),

    path("signup/", views.sign_up, name='sign_up'),
    path('signin/', views.sign_in, name='sign_in'),

    path('create/', views.create, name='create'),
    path('board/', views.board, name='board'),

    path('logout/', views.logout, name='logout'),
    path('about/', views.about, name='about'),
    path('settings/', views.settings, name='settings'),

    path('del_note/<int:note_id>/', views.del_note, name='del_note'),
    path('edit_note/<int:note_id>/', views.edit_note, name='edit_note'),

    path('ajax', AjaxHandlerView.as_view()),

    path('share/create/<int:note_id>', snote.create, name="snote_create"),
    path('share/<unique_id>', snote.shared, name="snote_shared")
    # path('share/', include("sharedNotes.urls")),
    # path('<int:algorithm_id>/', views.detail, name='detail'),
    # path('<int:algorithm_id>/leave_comment/', views.leave_comment, name='leave_comment'),
]

templates/board/about.html
{% extends 'board/base.html' %}

{% block title %}
    Обо мне
{% endblock %}

{% block content %}
    <h1>Что я могу сказать о себе?</h1>
    <p>Я умный и довольно потешный паренек</p>
    <p>Почта: {{ user.user_email }}</p>
{% endblock %}

templates/board/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<meta http-equiv="cache-control" content="no-cache">
<meta http-equiv="expires" content="0">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <style>

    </style>

    <script type="text/javascript"
            src="{% static 'js/jquery.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'board/bootstrap.min.css' %}">


    <script type="text/javascript"
            src="{% static 'board/bootstrap.bundle.min.js' %}"></script>
    <script type="text/javascript"
            src="{% static 'js/main.js' %}"></script>
    {% block header %}
    {% endblock %}

</head>
<body>

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
 <a class="navbar-brand" href="#">
    <img src="{% static 'login/images/logo500.png' %}" width="60" height="30" class="d-inline-block align-top" alt="EasyNotes">
  </a>
    <h5 class="my-0 mr-md-auto font-weight-normal">{% block username %}{% endblock %}</h5>
    <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="{% url 'notes:board' %}">Главная</a>
        <a class="p-2 text-dark" href="{% url 'notes:about' %}">Обо мне</a>
        <a class="p-2 text-dark" href="#" data-toggle="modal" data-target="#exampleModal">Создать заметку</a>
        <a class="p-2 text-dark" href="{% url 'notes:settings' %}">Настройки</a>
    </nav>
    <a class="btn btn-outline-primary" href="{% url 'notes:logout' %}">Выход</a>
</div>


<div class="container">
    {% block content %}{% endblock %}
</div>

<div class="modal fade bd-example-modal-lg" id="exampleModal" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Новая заметка</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" id="form_push">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Название:</label>
                        {{ form.note_title }}
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Текст:</label>
                        {{ form.note_text | safe }}
                        {{ form.media }}
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Тэги:</label>
                        {{ form.note_tags }}
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button type="button" id="push_btn" data-dismiss="modal" class="btn btn-info">Сохранить</button>
            </div>
        </div>
    </div>
</div>


<div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Предпупреждение.</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Заметка неверно заполнена!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


</body>
</html>

templates/board/create.html
{% extends 'board/base.html' %}

{% block title %}
Добавить заметку
{% endblock %}

{% block content %}
<h1>Создать заметку</h1>
<form method="post" >
      {% csrf_token %}
      {{form.note_title}}<br>
      {{form.note_text}}<br>
      {{ form.media }}
      {{form.note_tags}}<br>
      <button type="submit" class="btn btn-success">Добавить</button>
      <span>{{error}}</span>
</form>
{% endblock %}

templates/board/editer.html
{% extends 'board/base.html' %}

{% block title %}
    Изменение заметки
{% endblock %}

{% block content %}
    <h1>Изменить заметку</h1>
    <form method="post">
        {% csrf_token %}
        {{ editform.note_title }}<br>
        {{ editform.note_text| safe }}
        {{ form.media }}<br>
        {{ editform.note_tags }}<br>
        <button type="submit" class="btn btn-info">Сохранить</button>
        <span>{{ error }}</span>
    </form>


{% endblock %}

templates/board/index.html
{% extends 'board/base.html' %}
{% load static %}
{% block title %}
    Доска
{% endblock %}
{% block header %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'board/style.css' %}">



{% endblock %}

{% block username %}
    {{ user.user_name }}
{% endblock %}
{% block content %}



    {% if note %}
        {% for el in note %}
            <div class="container mt-1 ">

                <div class="d-flex justify-content-center row ">

                    <div class="col-md-10 shadow-lg p-3 mb-5 bg-white rounded">
                        <div class="btn-group-vertical pull-right" style="margin-right: 10px">
                            <a href="{% url 'notes:del_note' el.id %}" type="button" class="btn btn-link pull-right">
                                <h5><i class="fa fa-times text-info"
                                       aria-hidden="true"></i></h5>
                            </a>
                            <a href="{% url 'notes:edit_note' el.id %}" type="button" class="btn btn-link"><h5><i
                                    class="fa fa-pencil text-info"
                                    aria-hidden="true"></i></h5></a>
                            <a href="{% url 'notes:snote_create' el.id %}" type="button" class="btn btn-link"><h5><i
                                    class="fa fa-file-o text-info"
                                    aria-hidden="true"></i></h5></a>

                        </div>
                        <div class="p-6 bg-white notes ">
                            <div class="d-flex flex-row align-items-center notes-title " >
                                <h4 class="text-break" >{{ el.note_title }}</h4>
                            <ul class="list-group list-group-flush">
                                {% for a in el.get_tags %}
                                    <span class="px-2 review-text ml-2 rounded bg-info text-light mr-auto mb-1">{{ a }}</span>
                                {% endfor %}
                            </ul>

                            </div>
                            <div class="d-flex flex-row align-items-center align-content-center">
                                <span class="rounded info">{{ el.pub_date }}</span><span
                                    class="dot"></span></div>
                        </div>
                        <div class="text-break bg-white p-1"  >
                            <hr>
                            {{ el.note_text | safe }}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}








{% endblock %}

templates/board/settings.html
{% extends 'board/base.html' %}

{% block title %}
Настройки
{% endblock %}

{% block content %}
<h1>Здесь указаны настройки вашей учетной записи</h1>
{% endblock %}